module com.github.maeda6uiui.mechtatel.core {
    requires java.desktop;
    requires com.fasterxml.jackson.core;
    requires com.fasterxml.jackson.databind;
    requires com.github.dabasan.jxm.bd1;
    requires Libbulletjme;
    requires transitive org.slf4j;
    requires transitive org.joml;
    requires org.lwjgl;
    requires org.lwjgl.glfw;
    requires org.lwjgl.vulkan;
    requires org.lwjgl.shaderc;
    requires org.lwjgl.stb;
    requires org.lwjgl.assimp;
    requires org.lwjgl.openal;
    requires transitive imgui.binding;
    requires com.github.maeda6uiui.mechtatel.natives;
    requires com.sun.jna;

    exports com.github.maeda6uiui.mechtatel.core;
    exports com.github.maeda6uiui.mechtatel.core.fseffect;
    exports com.github.maeda6uiui.mechtatel.core.camera;
    exports com.github.maeda6uiui.mechtatel.core.screen.component;
    exports com.github.maeda6uiui.mechtatel.core.input.keyboard;
    exports com.github.maeda6uiui.mechtatel.core.input.mouse;
    exports com.github.maeda6uiui.mechtatel.core.physics;
    exports com.github.maeda6uiui.mechtatel.core.postprocessing.blur;
    exports com.github.maeda6uiui.mechtatel.core.postprocessing.fog;
    exports com.github.maeda6uiui.mechtatel.core.postprocessing.light;
    exports com.github.maeda6uiui.mechtatel.core.screen;
    exports com.github.maeda6uiui.mechtatel.core.shadow;
    exports com.github.maeda6uiui.mechtatel.core.sound;
    exports com.github.maeda6uiui.mechtatel.core.text;
    exports com.github.maeda6uiui.mechtatel.core.screen.texture;
    exports com.github.maeda6uiui.mechtatel.core.util;
    exports com.github.maeda6uiui.mechtatel.core.operation;
    exports com.github.maeda6uiui.mechtatel.core.vulkan;
    exports com.github.maeda6uiui.mechtatel.core.vulkan.nabor;
    exports com.github.maeda6uiui.mechtatel.core.vulkan.nabor.fseffect;
    exports com.github.maeda6uiui.mechtatel.core.vulkan.nabor.gbuffer;
    exports com.github.maeda6uiui.mechtatel.core.vulkan.nabor.postprocessing;
    exports com.github.maeda6uiui.mechtatel.core.vulkan.nabor.shadow;
    exports com.github.maeda6uiui.mechtatel.core.vulkan.screen;
    exports com.github.maeda6uiui.mechtatel.core.vulkan.screen.component;
    exports com.github.maeda6uiui.mechtatel.core.vulkan.screen.texture;
    exports com.github.maeda6uiui.mechtatel.core.vulkan.shader;
    exports com.github.maeda6uiui.mechtatel.core.model;
    exports com.github.maeda6uiui.mechtatel.core.model.helper;
    exports com.github.maeda6uiui.mechtatel.core.postprocessing;
    exports com.github.maeda6uiui.mechtatel.core.vulkan.shader.slang;
}