name: Deploy artifacts to Maven Central

on:
  workflow_call:
    secrets:
      ossrhUsername:
        required: true
      ossrhPassword:
        required: true
      gpgKeyId:
        required: true
      gpgPrivateKey:
        required: true
      gpgPassphrase:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Configure GPG
        run: |
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg
          echo "use-agent" > ~/.gnupg/gpg.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          echo "allow-loopback-pinentry" > ~/.gnupg/gpg-agent.conf
      - name: Import GPG private key
        run: |
          echo "${{secrets.gpgPrivateKey}}" | base64 --decode | gpg --batch --yes --import
          echo "${{secrets.gpgPassphrase}}" | gpg --batch --yes --pinentry-mode loopback --passphrase-fd 0 --edit-key ${{secrets.gpgKeyId}} trust quit
      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>ossrh</id>
                <username>${{secrets.ossrhUsername}}</username>
                <password>${{secrets.ossrhPassword}}</password>
              </server>
            </servers>
          </settings>
          EOF
      - name: Deploy to Maven Central
        run: |
          mvn clean deploy \
            -Dgpg.executable=gpg \
            -Dgpg.passphrase=${{secrets.gpgPassphrase}} \
            -Dgpg.pinentry-mode=loopback
