name: Deploy artifacts to Maven Central when pushed to GitHub repo

on:
  push:
    branches:
      - develop
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy-artifacts.yml
    secrets:
      ossrhUsername: ${{secrets.OSSRH_USERNAME}}
      ossrhPassword: ${{secrets.OSSRH_PASSWORD}}
      gpgKeyId: ${{secrets.GPG_KEY_ID}}
      gpgPrivateKey: ${{secrets.GPG_PRIVATE_KEY}}
      gpgPassphrase: ${{secrets.GPG_PASSPHRASE}}
